# Generated by Django 4.0.4 on 2022-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='전화번호')),
                ('auth_number', models.IntegerField(verbose_name='인증번호')),
            ],
            options={
                'verbose_name_plural': '휴대폰 인증 관리 페이지',
                'db_table': 'authentications',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='아이디')),
                ('pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=16, unique=True, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('phone_number', models.CharField(max_length=30, null=True, unique=True, verbose_name='전화번호')),
                ('birth', models.DateField(max_length=20, verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('선택', None), ('남성', '남성'), ('여성', '여성')], default='선택', max_length=5, verbose_name='성별')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'user',
            },
        ),
    ]
